### ISSUE TITLE
Can't signup more than 1 accounts, showing invalid always

### ISSUE THREAD

**Issue by shivamsouravjha** [shivamsouravjha/Let-us-travel#1]

**Comment by mani9896** [comment]
Tried your code with my own cluster , all other code exactly same, works totally fine.
You should look at cluster configuration , some issue on that part.

**Comment by shivamsouravjha** [comment]
I really have no clue what happened but it worked with Node.js 3.6+ version, few times I got a buy but sorted it out, works fine now.
